<#
.SYNOPSIS
    Notes-Bot Kit — установщик для Windows.

.DESCRIPTION
    1. Копирует runtime/ в $Env:LOCALAPPDATA\NotesBotKit (или в путь из -InstallRoot).
    2. Подставляет токен из .env в скопированный .env (или принимает -BotToken).
    3. Регистрирует watchdog в Планировщике задач Windows (при запуске пользователя, auto-restart).
    4. Запускает watchdog в текущей сессии для немедленного старта бота.

.PARAMETER BotToken
    Telegram bot token от @BotFather. Если не указан — берётся из .env наверху репозитория.

.PARAMETER InstallRoot
    Куда ставить. По умолчанию $Env:LOCALAPPDATA\NotesBotKit.

.PARAMETER SourceRoot
    Корень notes-bot-kit-v1 (где лежит runtime/, install.ps1). По умолчанию — родитель install.ps1.

.PARAMETER SkipScheduledTask
    Не регистрировать Планировщик задач. Только запустить watchdog в текущей сессии.

.EXAMPLE
    .\install.ps1 -BotToken "1234567890:AAHxYz..."
    .\install.ps1                              # токен из .env рядом с install.ps1
    .\install.ps1 -InstallRoot D:\NotesBotKit  # кастомный путь

.NOTES
    Автор: Notes-Keeper (📓). Версия: v1.
    Требует: PowerShell 5.1+ (Windows 10/11), Python 3.10+ в PATH или NOTES_BOT_PYTHON.
#>

[CmdletBinding()]
param(
    [string]$BotToken,
    [string]$InstallRoot,
    [string]$SourceRoot,
    [switch]$SkipScheduledTask
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
if (-not $SourceRoot) { $SourceRoot = $ScriptDir }
if (-not $InstallRoot) { $InstallRoot = Join-Path $env:LOCALAPPDATA "NotesBotKit" }

Write-Host "============================================================" -ForegroundColor Cyan
Write-Host " Notes-Bot Kit — installer" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Source : $SourceRoot"
Write-Host "Install: $InstallRoot"

# ---------- 1. Source sanity ----------
$RuntimeSrc = Join-Path $SourceRoot "runtime\scripts"
if (-not (Test-Path (Join-Path $RuntimeSrc "telegram_notes_bot.py"))) {
    throw "Не найден runtime/scripts/telegram_notes_bot.py в $SourceRoot. Проверь путь."
}

# ---------- 2. Token resolution ----------
if (-not $BotToken) {
    $EnvExample = Join-Path $SourceRoot ".env.example"
    $EnvLocal   = Join-Path $SourceRoot ".env"
    $EnvSource  = if (Test-Path $EnvLocal) { $EnvLocal } elseif (Test-Path $EnvExample) { $EnvExample } else { $null }
    if ($EnvSource) {
        Get-Content $EnvSource | ForEach-Object {
            if ($_ -match '^\s*TEAM_BOT_TOKEN\s*=\s*(.+)$') { $script:BotToken = $Matches[1].Trim() }
        }
    }
}
if (-not $BotToken) {
    throw "Токен не найден. Укажи -BotToken '...' или создай .env рядом с install.ps1 (см. .env.example)."
}
if ($BotToken -notmatch '^\d{6,12}:[A-Za-z0-9_-]{30,}$') {
    Write-Warning "Токен выглядит подозрительно (ожидаю формат `<id>:<35+ chars>`). Всё равно продолжу — проверишь в Telegram."
}

# ---------- 3. Copy runtime ----------
Write-Host ""
Write-Host "[1/5] Копирую runtime в $InstallRoot ..." -ForegroundColor Yellow
if (Test-Path $InstallRoot) {
    Write-Host "  Папка уже есть — обновляю runtime (конфиг и .env НЕ трогаю)." -ForegroundColor DarkYellow
    Copy-Item -Path (Join-Path $RuntimeSrc "*") -Destination (Join-Path $InstallRoot "scripts") -Recurse -Force
} else {
    New-Item -ItemType Directory -Force -Path (Join-Path $InstallRoot "scripts") | Out-Null
    Copy-Item -Path (Join-Path $RuntimeSrc "*") -Destination (Join-Path $InstallRoot "scripts") -Recurse -Force
}
Copy-Item -Path (Join-Path $SourceRoot "runtime\workspace\memory\bot-config.template.json") -Destination (Join-Path $InstallRoot "memory\bot-config.json") -Force
Copy-Item -Path (Join-Path $SourceRoot "runtime\workspace\memory\members.template.json") -Destination (Join-Path $InstallRoot "memory\members.json") -Force
New-Item -ItemType Directory -Force -Path (Join-Path $InstallRoot "memory\inbox") | Out-Null
New-Item -ItemType File -Path (Join-Path $InstallRoot "memory\notes.jsonl") -Force | Out-Null

# ---------- 4. .env ----------
Write-Host "[2/5] Записываю .env ..." -ForegroundColor Yellow
$OpenClawEnvPath = Join-Path $env:USERPROFILE ".openclaw\.env"
$envContent = @"
# Notes-Bot Kit — generated by install.ps1 at $(Get-Date -Format o)
TEAM_BOT_TOKEN=$BotToken
TELEGRAM_BOT_TOKEN=$BotToken
"@
# В двух местах: внутри kit (для удобства) и в ~/.openclaw/.env (если папка есть).
$KitEnv = Join-Path $InstallRoot ".env"
Set-Content -LiteralPath $KitEnv -Value $envContent -Encoding UTF8
if (Test-Path (Split-Path -Parent $OpenClawEnvPath)) {
    # Дополняем существующий ~/.openclaw/.env, не перетирая чужие переменные.
    $existing = @{}
    if (Test-Path $OpenClawEnvPath) {
        Get-Content $OpenClawEnvPath | ForEach-Object {
            if ($_ -match '^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)$') { $existing[$Matches[1]] = $Matches[2] }
        }
    }
    $existing["TEAM_BOT_TOKEN"] = $BotToken
    $existing["TELEGRAM_BOT_TOKEN"] = $BotToken
    $merged = ($existing.GetEnumerator() | ForEach-Object { "$($_.Key)=$($_.Value)" }) -join "`n"
    Set-Content -LiteralPath $OpenClawEnvPath -Value $merged -Encoding UTF8
    Write-Host "  .env также дополнен: $OpenClawEnvPath" -ForegroundColor DarkGray
}

# ---------- 5. Python autodetect ----------
Write-Host "[3/5] Ищу Python ..." -ForegroundColor Yellow
$Python = $env:NOTES_BOT_PYTHON
if (-not $Python) {
    $Candidates = @(
        "C:\Users\Admin\AppData\Local\Programs\Python\Python312\python.exe",  # Karim's default
        "C:\Python312\python.exe",
        "C:\Python311\python.exe",
        "C:\Python310\python.exe"
    )
    foreach ($p in $Candidates) { if (Test-Path $p) { $Python = $p; break } }
    if (-not $Python) {
        $py = (Get-Command python -ErrorAction SilentlyContinue).Source
        if ($py -and ($py -notmatch "WindowsApps")) { $Python = $py }
    }
}
if (-not $Python) {
    Write-Warning "Python не найден автоматически. Установи Python 3.10+ и запусти install.ps1 заново, либо задай `$env:NOTES_BOT_PYTHON."
} else {
    $ver = & $Python --version 2>&1
    Write-Host "  Python: $Python ($ver)" -ForegroundColor Green
    $verNum = ($ver -replace '[^\d.]','')
    if ([version]$verNum -lt [version]"3.10") {
        Write-Warning "Python $verNum < 3.10. Бот может не запуститься (использует match-statement, | type hints)."
    }
}

# ---------- 6. pip deps ----------
if ($Python) {
    Write-Host "[4/5] Проверяю зависимости (aiogram, aiohttp) ..." -ForegroundColor Yellow
    $need = @()
    foreach ($p in "aiogram","aiohttp") {
        $probe = & $Python -c "import importlib,sys; importlib.import_module('$p'); print('ok')" 2>&1
        if ($LASTEXITCODE -ne 0) { $need += $p }
    }
    if ($need.Count -gt 0) {
        Write-Host "  Устанавливаю: $($need -join ', ')" -ForegroundColor Yellow
        & $Python -m pip install --upgrade pip 2>&1 | Out-Null
        & $Python -m pip install $need 2>&1 | Out-Null
    } else {
        Write-Host "  Все зависимости уже стоят." -ForegroundColor Green
    }
}

# ---------- 7. Scheduled task (watchdog auto-start) ----------
$TaskName = "NotesBotKitWatchdog"
if (-not $SkipScheduledTask) {
    Write-Host "[5/5] Регистрирую watchdog в Планировщике задач (имя: $TaskName) ..." -ForegroundColor Yellow
    if (-not $Python) { Write-Warning "  Пропускаю (нет Python). Запусти watchdog вручную: .\scripts\telegram_notes_bot_watchdog.py"; }
    else {
        $Action = New-ScheduledTaskAction -Execute $Python -Argument "`"$InstallRoot\scripts\telegram_notes_bot_watchdog.py`"" -WorkingDirectory "$InstallRoot\scripts"
        $Trigger = New-ScheduledTaskTrigger -AtLogOn
        $Settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -RestartCount 99 -RestartInterval (New-TimeSpan -Minutes 1)
        $Principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Highest
        Register-ScheduledTask -TaskName $TaskName -Action $Action -Trigger $Trigger -Settings $Settings -Principal $Principal -Force | Out-Null
        Write-Host "  Scheduled task создан. Запустится при следующем логине." -ForegroundColor Green
    }
} else {
    Write-Host "[5/5] -SkipScheduledTask — пропускаю регистрацию в Планировщике." -ForegroundColor DarkYellow
}

# ---------- 8. Запуск прямо сейчас ----------
Write-Host ""
Write-Host "Запускаю watchdog в текущей сессии (Ctrl+C для остановки) ..." -ForegroundColor Cyan
Write-Host "Лог: $InstallRoot\scripts\telegram_notes_bot.watchdog.log" -ForegroundColor DarkGray
Write-Host ""
if ($Python) {
    & $Python "$InstallRoot\scripts\telegram_notes_bot_watchdog.py"
} else {
    Write-Warning "Не могу запустить — Python не найден. Поставь Python и выполни вручную: python `$InstallRoot\scripts\telegram_notes_bot_watchdog.py"
}
